In [1]:
# Provided code
import numpy as np

#The rest of this cell for for for making the output nice.

import sympy as sym
sy = sym
import IPython
from IPython.display import display
space= "\hspace{2.5cm}"

def displayLatex(latexCode):
    display( IPython.core.display.Math(latexCode) )


def displayEquation(LHS, RHS):     #Does not work inside of a print statement
    latex_left  = sy.latex(LHS)
    latex_right = sy.latex(RHS)
    display( IPython.core.display.Math(latex_left + "=" + latex_right) )


def displayH(a1,a2='', a3='', a4='', a5='', a6='',a7='',a8='', ):
    latex_a1 = sy.latex(a1)
    latex_a2 = sy.latex(a2)
    latex_a3 = sy.latex(a3)
    latex_a4 = sy.latex(a4)
    latex_a5 = sy.latex(a5)
    latex_a6 = sy.latex(a6)
    latex_a7 = sy.latex(a7)
    latex_a8 = sy.latex(a8)
    display( IPython.core.display.Math(latex_a1 + latex_a2 + latex_a3 + latex_a4 + latex_a5 + latex_a6 + latex_a7 + latex_a8 )  )

### Basic Matrix Operations

**<span style="color:red">
Just a reminder: Copying code is considered to be cheating. Using code from another semester, a friend, the web, etc. is an honor code violation. If you are lost, contact me or the TA to get help.</span>**

#### **1. For each of the matrix operations listed below,**


- **Part 1:**  Write code that performs the operation by using some amount of colon notation. The code from lab only used loops, so there is room for improvement.

- **Part 2:**  Use a Python function or a function from NumPy, such as `matmul`, that is designed to accomplish each operation.

**Warning:** Do not hard code the array dimensions when you write a function. For example, your matrix times matrix code should also work for a 10x10 matrix times a 10x20 matrix. Only the cross product may be hard-coded (for 3D vectors).

**Operations**
1. The dot product: $A \cdot B$
2. The cross product: $A \times B$
3. Matrix times a vector: $CA$
4. Matrix times a matrix: $CD$

**You should perform all indicated operations by hand before programming. Your hand calculations are not to be turned in this time, but they are still important practice.**

**Here are the arrays:**

In [2]:
A = np.array([3,4,8])
B = np.array([6,2,1])
C = np.array([[2,9,7],[3,4,1],[1,6,5]])
D = np.array([[4,3],[1,6],[8,7]])
displayH('A =',sym.Matrix(A), '      B =', sym.Matrix(B))
print('')
displayH('C =', sym.Matrix(C), '     D =', sym.Matrix(D) )

# print(A.size,B.size,C.size,D.size)
# print(A.shape,B.shape,C.shape,D.shape)

<IPython.core.display.Math object>

<IPython.core.display.Math object>

#### **Part 1 - Colon notation**

In [3]:
# 1. Vector dot vector: A.B
def Dot(A, B):
    sum = 0
    for i in range(len(A)):
        sum += A[i] * B[i]
    return sum

# 2. Vector x vector: A cross B
def Cross(A, B):
    cross = [
    A[1]*B[2] - B[1]*A[2],
    -(A[0]*B[2] - A[2]*B[0]),
    A[0]*B[1] - A[1]*B[0]
    ]
    return cross

# 3. Matrix*Vector: CA
def MatrixVector(M, V):
    result = np.zeros(V.shape[0])
    for rowNum in range(M.shape[0]):
        for colNum in range(M.shape[0]):
            result[rowNum] = result[rowNum] + M[rowNum, colNum] * V[colNum]
    return result

# 4. Matrix*Matrix: CD
def MatrixMatrix(A, B):
    result = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                result[i, j] += A[i, k] * B[k, j]
    return(result)

print(f"The dot product A.B = {Dot(A, B)}")
print(f"The cross product AxB is: {Cross(A, B)}")
print(f"Matrix * Vector: [C][A] = {MatrixVector(C, A)}")
print(f"Matrix*Matrix: [C][D] = \n{MatrixMatrix(C, D)}")

The dot product A.B = 34
The cross product AxB is: [-12, 45, -18]
Matrix * Vector: [C][A] = [98. 33. 67.]
Matrix*Matrix: [C][D] = 
[[ 73. 109.]
 [ 24.  40.]
 [ 50.  74.]]


#### **Part 2 - NumPy built-in functions**

In [4]:
# 1. Vector dot vector: A.B
print(f"The dot product A.B = {np.dot(A, B)}")

# 2. Vector x vector: A cross B
print(f"The cross product AxB is: {np.cross(A, B)}")

# 3. Matrix*Vector: CA
print(f"Matrix * Vector: [C][A] = {np.dot(C, A)}")

# 4. Matrix*Matrix: CD
print(f"Matrix*Matrix: [C][D] = \n{np.dot(C, D)}")

The dot product A.B = 34
The cross product AxB is: [-12  45 -18]
Matrix * Vector: [C][A] = [98 33 67]
Matrix*Matrix: [C][D] = 
[[ 73 109]
 [ 24  40]
 [ 50  74]]


#### **2. Multiplication of triangular matrices**

This problem will use the triangular matrix **L** and its transpose to calculate these products:

* $L\,L$

* $L\,{L^T}$

In [5]:
#provided code

print('The matrix L is:\n')
L = np.array([[1,0,0,0],[2,3,0,0],[4,5,6,0],[7,8,8,10]],dtype=float)
displayEquation( 'L', sy.Matrix(L) )
print('\nTo help you check your answers, here are the two products:\n')
displayH('L @ L=',sym.Matrix(L @L),'       L @ L.T=',sym.Matrix(L @ L.T) )

print('\nBelow is L with the zeros replaced with nan. You will use this definition of L for your python code.\n')
tmp = float('nan')
L  = np.array([[1,tmp,tmp,tmp],[2,3,tmp,tmp],[4,5,6,tmp],[7,8,8,10]],dtype=float)
#displayEquation('L', sym.Matrix(L) )
print('L=\n',L)

The matrix L is:



<IPython.core.display.Math object>


To help you check your answers, here are the two products:



<IPython.core.display.Math object>


Below is L with the zeros replaced with nan. You will use this definition of L for your python code.

L=
 [[ 1. nan nan nan]
 [ 2.  3. nan nan]
 [ 4.  5.  6. nan]
 [ 7.  8.  8. 10.]]


2a) The first task is to calculate the matrix products by hand, which should match those above. You do not need to turn this in.

2b) The second task is to  write Python code to do the calculations. Your Python code must avoid multiplying terms that are known to be zero because L is a lower triangular matrix. **You should NOT use conditionals to avoid these terms;** to do so would be obscenely inefficient! To confirm that you are avoiding the zeros, we replaced the zeros in the matrix L with "not a number", which is denoted by `nan`. If any of your calculations involve `nan`, it will be obvious, since the result will also be `nan`. Your code must be able to handle any size of lower triangular matrix.  Also, **do not take advantage of any resulting matrix being symmetric.**

In [6]:
# L L

sideLength = np.shape(L)[1]

newL = np.zeros_like(L)

for rowNum in range(sideLength):
    row = L[rowNum, 0:rowNum+1] #gets row without 0s without splicing yet
    rowLength = len(row) #length of that row
    for coluNum in range(rowLength): #length of row also determines how many calculations without 0 there will be (columns)
        column = L[:, coluNum] #full column
        newCol = column[coluNum:rowLength] #spliced column
        newRow = row[coluNum:] #spliced row
        # value = Dot(newRow, newCol) #actual dot product
        newL[rowNum, coluNum] = Dot(newRow, newCol) #insertion of value
        # print(f"row: {newRow}\ncol: {newCol}\ndot: {value}\n")
    # print(f"Completed Row Index {rowNum}\n")

displayEquation('newL', sym.Matrix(newL))

<IPython.core.display.Math object>

In [7]:
# L L.T
L = np.array([[1,0,0,0],[2,3,0,0],[4,5,6,0],[7,8,8,10]],dtype=float)
newL = np.zeros_like(L)

sideLength = np.shape(L)[0]

for rowNum in range(sideLength):
    for colNum in range(sideLength):
        newL[rowNum, colNum] = sum(L[rowNum, :rowNum + 1] * L[colNum, :rowNum + 1])

#so much time for such little code
#different approach

displayEquation('newL', sym.Matrix(newL))

<IPython.core.display.Math object>

#### **3. Zeroing out terms outside a band**
The matrix $A$ shown below is fully populated with non-zero terms. Your task is to write a general function that takes a square matrix and zeros out the terms on each row that lie beyond some distance `HBW` (Half Band-Width) from the diagonal. The maximum number of non-zero terms on any row will be 2*`HBW` + 1.
You will test your code on the matrix $A$ and use `HBW = 3`.

To make sure you understand what the matrix should look like, we have also included what it should look like after your function modifies it.

In [8]:
# Provided code

import numpy as np
A = np.array([1,2,3,4,5,6,7,8,9,10,11])
A = np.outer(A,A)
n = np.shape(A)[0]
for i in range(n): A[i,i]= -1
print('Original matrix:\n'); displayEquation('A', sy.Matrix(A))

Original matrix:



<IPython.core.display.Math object>

**This is what your matrix should look like after modification:**

**After modification,**
$\displaystyle A=\left[\begin{array}{ccccccccccc}-1 & 2 & 3 & 4 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\2 & -1 & 6 & 8 & 10 & 0 & 0 & 0 & 0 & 0 & 0\\3 & 6 & -1 & 12 & 15 & 18 & 0 & 0 & 0 & 0 & 0\\4 & 8 & 12 & -1 & 20 & 24 & 28 & 0 & 0 & 0 & 0\\0 & 10 & 15 & 20 & -1 & 30 & 35 & 40 & 0 & 0 & 0\\0 & 0 & 18 & 24 & 30 & -1 & 42 & 48 & 54 & 0 & 0\\0 & 0 & 0 & 28 & 35 & 42 & -1 & 56 & 63 & 70 & 0\\0 & 0 & 0 & 0 & 40 & 48 & 56 & -1 & 72 & 80 & 88\\0 & 0 & 0 & 0 & 0 & 54 & 63 & 72 & -1 & 90 & 99\\0 & 0 & 0 & 0 & 0 & 0 & 70 & 80 & 90 & -1 & 110\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 88 & 99 & 110 & -1\end{array}\right]$

In [9]:
# newA = np.zeros_like(A)

HBW = 3
sideLength = np.shape(A)[0]

for rowNum in range(sideLength):
    for colNum in range(sideLength):
        A[rowNum, (colNum + rowNum + 1 + HBW):] = 0
        A[(colNum + rowNum + 1 + HBW):, rowNum] = 0

#beautiful
        
displayEquation('A', sy.Matrix(A))

<IPython.core.display.Math object>