#### **Iterative Solvers**

**Assignment:  problems H1, H2, P1, P2**

**Hand calculation for small arrays (rank = 3 or 4)**

Use zeros as the initial guess for the solution. Perform 4 iterations. Do not worry about over/under relaxation.

H1) Gauss Seidel: Problem 11, p. 99. Swap rows to **make the system diagonally dominant** prior to iterating.

H2) Jacobi: Problem 12, p. 99. **Use the Jacobi method** instead of what is in the book.

**Logic/Programming questions**
* For both P1 and P2, use the arrays $A$ and $B$ from the following code cell.
* Remember `.copy()` can help you avoid changing variables you do not wish to change.

In [2]:
#Code provided
%reset -f
import numpy as np

n = 6  # size of the square coefficient matrix to be created
np.random.seed(5)
A = np.array(np.random.uniform(size=n*n))
B = np.array(np.random.uniform(size=n))
A = A.reshape(n,n)
B = B.reshape(n,1)
A = A + n*np.eye(n, dtype=float)  # Diagonally dominant coefficient matrix

x0 = np.array([0.,0.,0.,0.,0.,0.])
x0 = x0.reshape(n,1)  # Starting guess

print('A=\n',A,'\nB=\n',B,'\nx0 (starting guess)=\n',x0)

A=
 [[6.22199317 0.87073231 0.20671916 0.91861091 0.48841119 0.61174386]
 [0.76590786 6.51841799 0.2968005  0.18772123 0.08074127 0.7384403 ]
 [0.44130922 0.15830987 6.87993703 0.27408646 0.41423502 0.29607993]
 [0.62878791 0.57983781 0.5999292  6.26581912 0.28468588 0.25358821]
 [0.32756395 0.1441643  0.16561286 0.96393053 6.96022672 0.18841466]
 [0.02430656 0.20455555 0.69984361 0.77951459 0.02293309 6.57766286]] 
B=
 [[0.00164217]
 [0.51547261]
 [0.63979518]
 [0.9856244 ]
 [0.2590976 ]
 [0.80249689]] 
x0 (starting guess)=
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


P1)  Write a function that uses the **Jacobi method** to solve a set of equations. Follow these instructions:
* Given that $Ax = B$, your function will be passed $A$, $B$, and a starting guess and will return the solution $x$.
* Your function should get the maximum absolute residual within a tolerance of 1.0E-12.
* Your function should print out the maximum absolute residual for each iteration.
* Demonstrate your function by solving the provided set of 6 equations.
* Check the accuracy of your solution by comparing your solution with the output of a NumPy solver.
* You are not required to implement over/under relaxation.

In [34]:
#P1 Jacobi
A = np.array([[7, 1, 1], [-3, 7, -1], [-2, 5, 9]])
B = np.array([[6], [-26], [1]])

def Jacobi(A,b,tol,x):
    length = np.shape(A)[0]
    # for rowNum in range(length):
    #     for colNum in range(length):
    #         print(A[rowNum, colNum])

    for rowNum in range(length):
        row = A[rowNum]
        print(row)
        bVal = B[rowNum, 0]
        diagonalValue = row[rowNum]
        print(f"Equation = ") 
        for colNum in range(length):
            if colNum != rowNum:
                print(f"-{row[colNum]}", end = None)

        # xi = (bVal - row[0])/diagonalValue
        
        

    #Rn = A*xn - B
    #A*xn should approach B, 
    #therefore the guessed value - actual value is the residual 

    return None

print(Jacobi(A.copy(), B.copy(), 1.0e-12, x0))

[7 1 1]
Equation = 
1 - 
1 - 
[-3  7 -1]
Equation = 
-3 - 
-1 - 
[-2  5  9]
Equation = 
-2 - 
5 - 
None


P2) Write a function that uses the **Gauss-Seidel method** to solve a set of equations. The instructions are the same:
* Given that $Ax = B$, your function will be passed $A$, $B$, and a starting guess and will return the solution $x$.
* Your function should get the maximum absolute residual within a tolerance of 1.0E-12.
* Your function should print out the maximum absolute residual for each iteration.
* Demonstrate your function by solving the provided set of 6 equations.
* Check the accuracy of your solution by comparing your solution with the output of a NumPy solver.
* You are not required to implement over/under relaxation.

In [4]:
# P2 Gauss-Seidel

def GaussSeidel(A,b,tol,x):
  pass
