#### **Iterative Solvers**

**Assignment:  problems H1, H2, P1, P2**

**Hand calculation for small arrays (rank = 3 or 4)**

Use zeros as the initial guess for the solution. Perform 4 iterations. Do not worry about over/under relaxation.

H1) Gauss Seidel: Problem 11, p. 99. Swap rows to **make the system diagonally dominant** prior to iterating.

H2) Jacobi: Problem 12, p. 99. **Use the Jacobi method** instead of what is in the book.

**Logic/Programming questions**
* For both P1 and P2, use the arrays $A$ and $B$ from the following code cell.
* Remember `.copy()` can help you avoid changing variables you do not wish to change.

In [1]:
#Code provided
%reset -f
import numpy as np

n = 6  # size of the square coefficient matrix to be created
np.random.seed(5)
A = np.array(np.random.uniform(size=n*n))
B = np.array(np.random.uniform(size=n))
A = A.reshape(n,n)
B = B.reshape(n,1)
A = A + n*np.eye(n, dtype=float)  # Diagonally dominant coefficient matrix

x0 = np.array([0.,0.,0.,0.,0.,0.])
x0 = x0.reshape(n,1)  # Starting guess

print('A=\n',A,'\nB=\n',B,'\nx0 (starting guess)=\n',x0)

A=
 [[6.22199317 0.87073231 0.20671916 0.91861091 0.48841119 0.61174386]
 [0.76590786 6.51841799 0.2968005  0.18772123 0.08074127 0.7384403 ]
 [0.44130922 0.15830987 6.87993703 0.27408646 0.41423502 0.29607993]
 [0.62878791 0.57983781 0.5999292  6.26581912 0.28468588 0.25358821]
 [0.32756395 0.1441643  0.16561286 0.96393053 6.96022672 0.18841466]
 [0.02430656 0.20455555 0.69984361 0.77951459 0.02293309 6.57766286]] 
B=
 [[0.00164217]
 [0.51547261]
 [0.63979518]
 [0.9856244 ]
 [0.2590976 ]
 [0.80249689]] 
x0 (starting guess)=
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


P1)  Write a function that uses the **Jacobi method** to solve a set of equations. Follow these instructions:
* Given that $Ax = B$, your function will be passed $A$, $B$, and a starting guess and will return the solution $x$.
* Your function should get the maximum absolute residual within a tolerance of 1.0E-12.
* Your function should print out the maximum absolute residual for each iteration.
* Demonstrate your function by solving the provided set of 6 equations.
* Check the accuracy of your solution by comparing your solution with the output of a NumPy solver.
* You are not required to implement over/under relaxation.

In [2]:
#P1 Jacobi Method

def Jacobi(A,B,tol,x0):
    length = np.shape(A)[0]
    residual = tol + 1
    iteration = 1
    x1 = x0.copy()
    while residual > tol:

        for rowNum in range(length):
            row = A[rowNum]
            bVal = B[rowNum, 0] #first term in equation
            diagonalValue = row[rowNum] #the diagonal value is the variable we're solving for
            # equationString = f"Equation x{rowNum} = ({bVal}" #represent the step in string form
            guess = bVal #all math occurs in result variable 

            #loop that performs the guess
            for colNum in range(length):
                if colNum != rowNum:
                    # equationString += f"-({row[colNum]} * {x0[colNum, 0]})"
                    guess -= row[colNum] * x0[colNum, 0] #-= since everything was moved to the other side when doing algebra
                    
            # equationString += f")/{diagonalValue}"
            guess /= diagonalValue

            # print(equationString)
            
            x1[rowNum, 0] = guess #updating x1 after the row, but not actually considered for next row

        x0 = x1.copy() #curse you .copy()!!! This line cost me an hour

        #this indent is when we have finished an iteration
        print(f"Iteration {iteration}:\n{x0}\n")

        #Rn = A*xn - B calculates the residuals
        residualList = np.matmul(A, x0) - B
        residual = abs(np.max(residualList))
        print(f"Max Residual of Iteration {iteration}: {residual}\n")

        iteration += 1

    return x0

print(f"Jacobi Soluton:\n{Jacobi(A.copy(), B.copy(), 1.0e-12, x0.copy())}")

print(f"\nNumpy solution:\n{np.linalg.solve(A.copy(), B.copy())}")

Iteration 1:
[[0.00026393]
 [0.0790794 ]
 [0.09299434]
 [0.15730176]
 [0.03722545]
 [0.12200335]]

Max Residual of Iteration 1: 0.32539594629433394

Iteration 2:
[[-0.05203377]
 [ 0.05600178]
 [ 0.07739933]
 [ 0.13442441]
 [ 0.0082748 ]
 [ 0.09087728]]

Max Residual of Iteration 2: 0.035403057459130194

Iteration 3:
[[-0.03957561]
 [ 0.06740035]
 [ 0.08527897]
 [ 0.14587644]
 [ 0.01559601]
 [ 0.0962596 ]]

Max Residual of Iteration 3: 0.02894230381531286

Iteration 4:
[[-0.04422722]
 [ 0.06454752]
 [ 0.0830889 ]
 [ 0.1422665 ]
 [ 0.01285441]
 [ 0.09363801]]

Max Residual of Iteration 4: 0.005106208288998437

Iteration 5:
[[-0.04274929]
 [ 0.06562871]
 [ 0.08387462]
 [ 0.14343766]
 [ 0.01375544]
 [ 0.09441431]]

Max Residual of Iteration 5: 0.003094649379623393

Iteration 6:
[[-0.04324666]
 [ 0.06528645]
 [ 0.08362063]
 [ 0.14304171]
 [ 0.01346159]
 [ 0.09414969]]

Max Residual of Iteration 6: 0.0005752472648633544

Iteration 7:
[[-0.04308278]
 [ 0.06540147]
 [ 0.08370526]
 [ 0.14317167

P2) Write a function that uses the **Gauss-Seidel method** to solve a set of equations. The instructions are the same:
* Given that $Ax = B$, your function will be passed $A$, $B$, and a starting guess and will return the solution $x$.
* Your function should get the maximum absolute residual within a tolerance of 1.0E-12.
* Your function should print out the maximum absolute residual for each iteration.
* Demonstrate your function by solving the provided set of 6 equations.
* Check the accuracy of your solution by comparing your solution with the output of a NumPy solver.
* You are not required to implement over/under relaxation.

In [3]:
#P2 GaussSeidel Method

def GaussSeidel(A,B,tol,x0):
    length = np.shape(A)[0]
    residual = tol + 1
    iteration = 1
    while residual > tol:

        for rowNum in range(length):
            row = A[rowNum]
            bVal = B[rowNum, 0] #first term in equation
            diagonalValue = row[rowNum] #the diagonal value is the variable we're solving for
            # equationString = f"Equation x{rowNum} = ({bVal}" #represent the step in string form
            guess = bVal #all math occurs in result variable 

            #loop that performs the guess
            for colNum in range(length):
                if colNum != rowNum:
                    # equationString += f"-({row[colNum]} * {x0[colNum, 0]})"
                    guess -= row[colNum] * x0[colNum, 0] #-= since everything was moved to the other side when doing algebra
                    
            # equationString += f")/{diagonalValue}"
            guess /= diagonalValue

            x0[rowNum, 0] = guess #update the guess after the row, so it can be used immediately if necessary in the next guess

            # print(equationString)

        #this indent is when we have finished an iteration
        print(f"Iteration {iteration}:\n{x0}\n")

        #Rn = A*xn - B calculates the residuals
        residualList = np.matmul(A, x0) - B
        residual = abs(np.max(residualList))
        print(f"Max Residual of Iteration {iteration}: {residual}\n")

        iteration += 1

    return x0

print(f"Gauss-Seidel Soluton:\n{GaussSeidel(A.copy(), B.copy(), 1.0e-12, x0.copy())}")

print(f"\nNumpy solution:\n{np.linalg.solve(A.copy(), B.copy())}")

Iteration 1:
[[0.00026393]
 [0.07904839]
 [0.09115847]
 [0.14123206]
 [0.01384729]
 [0.0930595 ]]

Max Residual of Iteration 1: 0.281103253699893

Iteration 2:
[[-0.04491504]
 [ 0.06542513]
 [ 0.08390488]
 [ 0.14332565]
 [ 0.0136192 ]
 [ 0.09417456]]

Max Residual of Iteration 2: 0.0008094865230373616

Iteration 3:
[[-0.04316837]
 [ 0.06536638]
 [ 0.08367653]
 [ 0.1431429 ]
 [ 0.01353877]
 [ 0.09421616]]

Max Residual of Iteration 3: 7.839067021675472e-06

Iteration 4:
[[-0.04312336]
 [ 0.06537304]
 [ 0.08368382]
 [ 0.14313904]
 [ 0.01353575]
 [ 0.09421548]]

Max Residual of Iteration 4: 1.8629274603776391e-06

Iteration 5:
[[-0.04312366]
 [ 0.06537297]
 [ 0.08368421]
 [ 0.1431392 ]
 [ 0.01353575]
 [ 0.09421542]]

Max Residual of Iteration 5: 1.3496745920882347e-07

Iteration 6:
[[-0.04312368]
 [ 0.06537295]
 [ 0.08368421]
 [ 0.14313921]
 [ 0.01353575]
 [ 0.09421542]]

Max Residual of Iteration 6: 2.493551698456997e-09

Iteration 7:
[[-0.04312368]
 [ 0.06537295]
 [ 0.08368421]
 [ 0.143