### **Lab 3: Matrix operations**

Given the vectors $A$ and $B$ and the matricies $C$ and $D$ below:

In [1]:
# Provided code

import numpy as np
import sympy as sym
import IPython
from IPython.display import display

def displayH(a1,a2='', a3='', a4='', a5='', a6='', ):
    latex_a1 = sym.latex(a1)
    latex_a2 = sym.latex(a2)
    latex_a3 = sym.latex(a3)
    latex_a4 = sym.latex(a4)
    latex_a5 = sym.latex(a5)
    latex_a6 = sym.latex(a6)
    display(IPython.core.display.Math(latex_a1 + latex_a2 + latex_a3 + latex_a4 + latex_a5 + latex_a6 ))

A = np.array([3,4,8])
B = np.array([6,2,1])
C = np.array([[2,9,7],[3,4,1],[1,6,5]])
D = np.array([[4,3],[1,6],[8,7]])
displayH('A=',sym.Matrix(A), '      B=', sym.Matrix(B))
print('')
displayH('C=', sym.Matrix(C), '     D=', sym.Matrix(D) )

<IPython.core.display.Math object>

<IPython.core.display.Math object>

#### **1. Complete the following operations by hand:**

1. The dot product: $A \cdot B$
2. The cross product: $A \times B$
3. Matrix times a vector: $CA$
4. Matrix times a matrix: $CD$

#### **2. Repeat task 1, but now use python**

Complete the operations in python **without** using any built in functions (e.g. `np.matmul`) or colon notation. Use only loops and your knowlege of matrix operations.



In [2]:
#1 Dot Product: A . B

def DotProduct(A, B):
    sum = 0
    for i in range(len(A)):
        sum += A[i] * B[i]
    return sum

print(f"The dot product A.B = {DotProduct(A, B)}")

The dot product A.B = 34


In [3]:
#2 Cross Product:  A x B

def CrossProduct(A, B):
    C = [
        A[1]*B[2] - B[1]*A[2],
        -(A[0]*B[2] - A[2]*B[0]),
        A[0]*B[1] - A[1]*B[0]
    ]
    return C

print(f"The cross product AxB is: {CrossProduct(A, B)}")

The cross product AxB is: [-12, 45, -18]


In [4]:
#3 Matrix * Vector:   [C][A]

def MatrixVector(M, V):
    sum = 0
    result = np.zeros(V.shape[0])
    for i in range(M.shape[0]):
        for j in range(M.shape[0]):
            result[i] = result[i] + M[i, j] * V[j]
    return result

print(f"Matrix * Vector: [C][A] = {MatrixVector(C, A)}")

Matrix * Vector: [C][A] = [98. 33. 67.]


In [5]:
#4 Matrix * Matrix:  [C][D]

def MatrixMatrix(A, B):
    R = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                R[i, j] += A[i, k] * B[k, j]
    return(R)

print(f"Matrix*Matrix: [C][D] = \n{MatrixMatrix(C, D)}")

Matrix*Matrix: [C][D] = 
[[ 73. 109.]
 [ 24.  40.]
 [ 50.  74.]]


#### **3. Use of colon notation**

Given the matrix:

$A = \begin{bmatrix}
  1 & 2 & 4 & 7 & 11 \\
  2 & 3 & 5 & 8 & 12 \\
  4 & 5 & 6 & 9 & 13 \\
  7 & 8 & 9 & 10 & 14 \\
  11 & 12 & 13 & 14 & 15 \\
\end{bmatrix}$

Replace all elements above the diagonal with zeros by iterating through the array with two nested `for` loops.

In [6]:
A = [[1,2,4,7,11],[2,3,5,8,12],[4,5,6,9,13],[7,8,9,10,14],[11,12,13,14,15]]
# n = np.shape(A)[0]  # Potentially useful! What is n here?

n = 0
newA = []
for oneList in A:
    n += 1
    firstHalf = oneList[0:n]
    for i in range(len(oneList) - n):
        firstHalf.append(0)
    newA.append(firstHalf)

A = np.array(A)
newA = np.array(newA)

print(f"Before:\n{A}\n")
print(f"After:\n{newA}")

Before:
[[ 1  2  4  7 11]
 [ 2  3  5  8 12]
 [ 4  5  6  9 13]
 [ 7  8  9 10 14]
 [11 12 13 14 15]]

After:
[[ 1  0  0  0  0]
 [ 2  3  0  0  0]
 [ 4  5  6  0  0]
 [ 7  8  9 10  0]
 [11 12 13 14 15]]


Perform the same operation above but use only one `for` loop and colon notation to eliminate the elements above the diagonal.

In [7]:
A = np.array([[1,2,4,7,11],[2,3,5,8,12],[4,5,6,9,13],[7,8,9,10,14],[11,12,13,14,15]])

n = np.shape(A)[0]

for i in range(n):
    A[i, (i+1):] = 0
print(A)

[[ 1  0  0  0  0]
 [ 2  3  0  0  0]
 [ 4  5  6  0  0]
 [ 7  8  9 10  0]
 [11 12 13 14 15]]


Print out each row using colon notation to exclude the elements above the diagonal.

In [8]:
for i in range(n):
    print(A[i, 0:i+1])

[1]
[2 3]
[4 5 6]
[ 7  8  9 10]
[11 12 13 14 15]


Create a matrix $B$ that is the transpose of the lower-diagonal $A$ using colon notation to move only the non-zero elements.

In [9]:
# Use colon notation to transpose lower diagonal A into upper diagonal B

B = np.zeros_like(A)
for i in range(n):
    B[0:i+1, i] = A[i, 0:i+1]
print(B)

[[ 1  2  4  7 11]
 [ 0  3  5  8 12]
 [ 0  0  6  9 13]
 [ 0  0  0 10 14]
 [ 0  0  0  0 15]]


Additional optional exercise: Identify functions from Numpy or another package that perform the same operations (dot product, cross product, matrix multiplication, and matrix transpose). Generate a large matrix and time them to see which is faster. Then try timing with different functions from `time` to see how they work.

In [10]:
# Do this for more practice and better understanding of useful functions